<%= ENV['RAILS_ENV'] %>:
  ONE: 
    host: <%= ENV['HEALTH_SFTP_HOST'] %>
    path: <%= ENV['HEALTH_SFTP_PATH'] %>
    username: <%= ENV['HEALTH_SFTP_USER'] %>
    password: <%= ENV['HEALTH_SFTP_PASS'] %>
    destination: <%= ENV['HEALTH_SFTP_DESTINATION'] %>
    data_source_name: 'BHCHP EPIC'